<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="148" started-at="2018-06-10T13:24:58Z" finished-at="2018-06-10T13:24:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="148" started-at="2018-06-10T13:24:58Z" finished-at="2018-06-10T13:24:58Z">
      <class name="restAPIFramework.CreatePersionAPITest">
        <test-method status="PASS" signature="dataSetup()[pri:0, instance:restAPIFramework.CreatePersionAPITest@23ceabc1]" name="dataSetup" is-config="true" duration-ms="33" started-at="2018-06-10T18:54:58Z" finished-at="2018-06-10T18:54:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataSetup -->
        <test-method status="FAIL" signature="createPersonAPITest()[pri:0, instance:restAPIFramework.CreatePersionAPITest@23ceabc1]" name="createPersonAPITest" duration-ms="22" started-at="2018-06-10T18:54:58Z" finished-at="2018-06-10T18:54:58Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
	List cannot be resolved to a type
	The method accept(String) is undefined for the type RequestSpecification
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
	List cannot be resolved to a type
	The method accept(String) is undefined for the type RequestSpecification

	at Service.Service.createPersonAPI(Service.java:24)
	at restAPIFramework.CreatePersionAPITest.createPersonAPITest(CreatePersionAPITest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPersonAPITest -->
      </class> <!-- restAPIFramework.CreatePersionAPITest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
